# Generated by Django 5.1.3 on 2024-12-01 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0002_category_alter_transaction_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="target",
            name="created_at",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Дата создания"
            ),
        ),
    ]
