# Generated by Django 5.1.3 on 2024-12-01 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0003_target_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="credit",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="credit",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="credit",
            name="term_months",
        ),
        migrations.AddField(
            model_name="credit",
            name="bank",
            field=models.CharField(default=None, max_length=100, verbose_name="Банк"),
        ),
        migrations.AddField(
            model_name="credit",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Выплачено"
            ),
        ),
        migrations.AddField(
            model_name="credit",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Сумма кредита"
            ),
        ),
    ]
