# Generated by Django 5.1.3 on 2024-12-01 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0004_remove_credit_amount_remove_credit_start_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="regularpayment",
            options={
                "ordering": ["next_payment_date"],
                "verbose_name": "Регулярный платеж",
                "verbose_name_plural": "Регулярные платежи",
            },
        ),
        migrations.RemoveField(
            model_name="regularpayment",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="regularpayment",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="regularpayment",
            name="start_date",
        ),
        migrations.AddField(
            model_name="regularpayment",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="operations.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="regularpayment",
            name="next_payment_date",
            field=models.DateField(null=True, verbose_name="Следующий платеж"),
        ),
        migrations.AlterField(
            model_name="regularpayment",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("weekly", "Еженедельно"),
                    ("monthly", "Ежемесячно"),
                    ("yearly", "Ежегодно"),
                ],
                max_length=10,
                verbose_name="Частота",
            ),
        ),
    ]
