# Generated by Django 5.1.3 on 2024-12-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0006_card_transaction_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="design",
            field=models.CharField(
                choices=[
                    ("classic_black", "Классическая черная"),
                    ("classic_white", "Классическая белая"),
                    ("gold", "Золотая"),
                    ("platinum", "Платиновая"),
                    ("metal", "Металлическая"),
                    ("red", "Красная"),
                    ("blue", "Синяя"),
                    ("green", "Зеленая"),
                    ("purple", "Фиолетовая"),
                    ("orange", "Оранжевая"),
                    ("teal", "Бирюзовая"),
                    ("pink", "Розовая"),
                    ("indigo", "Индиго"),
                    ("cyan", "Голубая"),
                    ("brown", "Коричневая"),
                ],
                default="classic_black",
                max_length=20,
                verbose_name="Дизайн карты",
            ),
        ),
    ]
